let product = [
  {
    title: 'Banana',
    img: '<img class="img-fluid rounded-start" src="./img/banan.jpg" alt="img">',
    count: 16,
    money: 2,
    all_money: 0,
    id: Math.round(Math.random() * 1000000000000),
    like: false,
  },
  {
    title: 'Apple',
    img: '<img class="img-apple" src="./img/apple.jpg" alt="img">',
    count: 8,
    money: 7,
    all_money: 0,
    id: Math.round(Math.random() * 1000000000000),
    like: false,
  },
  {
    title: 'Strawberry',
    img: '<img class="img-fluid rounded-start" src="./img/strawberry.jpg" alt="img">',
    count: 36,
    money: 14,
    all_money: 0,
    id: Math.round(Math.random() * 1000000000000),
    like: false,
  },
  {
    title: 'Apricot',
    img: '<img class="img-fluid rounded-start" src="./img/apricot.webp" alt="img">',
    count: 27,
    money: 5,
    all_money: 0,
    id: Math.round(Math.random() * 1000000000000),
    like: false,
  },
  {
    title: 'Cheery',
    img: '<img class="img-fluid rounded-start" src="./img/cherry.jpg" alt="img">',
    count: 67,
    money: 1,
    all_money: 0,
    id: Math.round(Math.random() * 1000000000000),
    like: false,
  },
  {
    title: 'Apelsin',
    img: '<img class="img-fluid rounded-start" src="./img/apelsin.jpg" alt="img">',
    count: 4,
    money: 7,
    all_money: 0,
    id: Math.round(Math.random() * 1000000000000),
    like: false,
  },
  {
    title: 'Limon',
    img: '<img class="img-fluid rounded-start" src="./img/limon.jpg" alt="img">',
    count: 3,
    money: 10,
    all_money: 0,
    id: Math.round(Math.random() * 1000000000000),
    like: false,
  },
  {
    title: 'Mandarin',
    img: '<img class="img-fluid rounded-start" src="./img/mandarin.jpg" alt="img">',
    count: 13,
    money: 4,
    all_money: 0,
    id: Math.round(Math.random() * 1000000000000),
    like: false,
  },
  {
    title: 'Avakado',
    img: '<img class="img-fluid rounded-start" src="./img/avakado.jpg" alt="img">',
    count: 27,
    money: 5,
    all_money: 0,
    id: Math.round(Math.random() * 1000000000000),
    like: false,
  },
  {
    title: 'Malina',
    img: '<img class="img-fluid rounded-start" src="./img/malina.png" alt="img">',
    count: 27,
    money: 5,
    all_money: 0,
    id: Math.round(Math.random() * 1000000000000),
    like: false,
  },
  {
    title: 'Anor',
    img: '<img class="img-fluid rounded-start" src="./img/anor.jpg" alt="img">',
    count: 37,
    money: 5,
    all_money: 0,
    id: Math.round(Math.random() * 1000000000000),
    like: false,
  },
  {
    title: 'Kiwi',
    img: '<img class="img-fluid rounded-start" src="./img/kiwi.jpg" alt="img">',
    count: 17,
    money: 2,
    all_money: 0,
    id: Math.round(Math.random() * 1000000000000),
    like: false,
  },
  {
    title: 'White-grapes',
    img: '<img class="img-fluid rounded-start" src="./img/grapes.jpg" alt="img">',
    count: 27,
    money: 5,
    all_money: 0,
    id: Math.round(Math.random() * 1000000000000),
    like: false,
  },
  {
    title: 'Black-grapes',
    img: '<img class="img-fluid rounded-start" src="./img/grapes2.png" alt="img">',
    count: 27,
    money: 5,
    all_money: 0,
    id: Math.round(Math.random() * 1000000000000),
    like: false,
  },
  
  
 
];

export { product }